version: "3.7"

services:
  app-flora_web:
    image: paulolopesestevao/flora-front:latest
    stdin_open: true
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: flora_web
    restart: always
    ports:
      - "3000:80"
    volumes:
      - "static_flora:/usr/srs/app/floraweb/build/static"
      - "/usr/srs/app/floraweb/node_modules"
      - "./:/usr/srs/app/floraweb"

volumes:
  static_flora: